### ISSUE TITLE
App Dev Title needs centering

### ISSUE THREAD

**Issue by grevollo** [nearshorecode/website#51]
![appdev issue](https://user-images.githubusercontent.com/40768369/42172796-14ab52c2-7deb-11e8-9494-dcc59768711e.png)

In the page for Application Development, that title is not centered. Development is towards the right.

**Comment by lmmantillac** [comment]
![fix issue 53](https://user-images.githubusercontent.com/20214581/43357409-f7b3115a-924e-11e8-9690-66f758fdd425.png)

Change the css to fix it.
