### ISSUE TITLE
Repeated Field

### ISSUE THREAD

**Issue by grevollo** [nearshorecode/website#57]
Whenever I try to change the Mobile Testing title and the subtitle below it, the same text appears in both. They might be linked, but we need to introduce independent texts in both.
![repeated title](https://user-images.githubusercontent.com/40768369/42294596-2d1ae0e0-7fb0-11e8-8e37-871eadb4e6f5.png)

**Comment by diegolanda** [comment]
@grevollo please review this issue to close it as solved or if any additional effort is needed still
