### ISSUE TITLE
Resize Boxes in Testing Services

### ISSUE THREAD

**Issue by grevollo** [nearshorecode/website#73]
I have modified the texts for the description of the Testing Services (some were too long). I think it would be best to reduce the length of the boxes longwise.
![testing services](https://user-images.githubusercontent.com/40768369/42845448-f8cbb16e-89e3-11e8-8b9a-c2aadcb4211e.png)

**Comment by lmmantillac** [comment]
![image](https://user-images.githubusercontent.com/20214581/43357563-a70d04f6-9251-11e8-8a54-90b17bb93dda.png)
css changed to fix it
