### ISSUE TITLE
Duration of promoted articles in Home Page

### ISSUE THREAD

**Issue by grevollo** [nearshorecode/website#74]
The seconds you have to read the promoted articles in the home page presentation are not enough to read title and subtitle. Maybe you can expand that duration or we can reduce the amount of text.
![home page articles](https://user-images.githubusercontent.com/40768369/43078566-e0d118f0-8e58-11e8-9d4e-74f07cdfa9b3.png)

**Comment by lmmantillac** [comment]
Update the interval time to 10 seconds, but we have to consider reduce the amount of text in the description part.
